export default {
    logo_img: require('../assets/images/icons-logo.png'),
    up_arrow: require('../assets/images/up-arrow.png'),
    invoice: require('../assets/images/camera.png'),
    active: require('../assets/images/trading.png'),
    transaction: require('../assets/images/counterflow.png'),
    overview: require('../assets/images/medium.png'),
    card_arrow: require('../assets/images/icon-up.png'),
    plus: require('../assets/images/icons-plus.png'),
    card_wifi: require('../assets/images/wifi.png'),
    increment: require('../assets/images/up-arrow.png'),
    down_arrow: require('../assets/images/down-arrow.png'),
    revenue: require('../assets/images/revenue.png'),
    bell: require('../assets/images/bell.png'),
    settings: require('../assets/images/settings.png'),
    chip: require('../assets/images/chip.png'),
    dark: require('../assets/images/dark.png'),
    brightness: require('../assets/images/brightness.png'),
    scrollDown: require('../assets/images/scroll-down.png'),
}